
app:

  # use the Dockerfile next to this file
  build: .

  # sources environment variable configuration for our app
  env_file: .env

  # rely on the RAILS_ENV value of the host machine
  environment:
    RAILS_ENV: $RAILS_ENV

  # makes the app container aware of the DB container
  links:
    - db

  # expose the port we configured Unicorn to bind to
  expose:
    - "3000"

db:
  environment:
    POSTGRES_USER:
    POSTGRES_PASSWORD:
  # use the preferred version of the official Postgres image
  # see https://hub.docker.com/_/postgres/
  image: postgres:9.4.5

  # persist the database between containers by storing it in a volume
  volumes:
    - food-postgres:/var/lib/postgresql/data

# service configuration for our web server
web:
 
  # set the build context to the root of the Rails app
  build: .
 
  # build with a different Dockerfile
  dockerfile: config/containers/Dockerfile-nginx

  environment:
    CA_SSL: "true"  

  # makes the web container aware of the app container
  links:
    - app
  
  volumes:
    - food-ssl:/var/www/ssl  
  # expose the port we configured Nginx to bind to
  ports:
    - "80:80"
    - "443:443"
