version: "2"

services:
  db:
   environment:
     POSTGRES_USER:
     POSTGRES_PASSWORD:
      image: postgres:9.5
      volumes:
        - db-data:/usr/local/pgsql/data

  app:
   build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
